### PR TITLE
added node 10 support

### PR DESCRIPTION
**Pull request by patricksmms**
I came across this lib and wanted to use it on a project I'm currently working on. The problem is that the project is still on node 10 and I can't update node ATM. Therefore doing this small change to support it.

### CODE REVIEW

**Comment by mainfraame** [comment]
@patricksmms Sorry to hear that, I don’t see any issues with making this change.  I’ll merge your PR, run a build and publish it later tonight.

**Comment by patricksmms** [comment]
@mainfraame Thank you very much!

**Comment by mainfraame** [comment]
@patricksmms i just published the version with your change in it. Please see the [CHANGELOG Notes](https://github.com/mainfraame/cucumber-jest/blob/master/CHANGELOG.md#notes); I noticed that after refactoring the function names, I needed to run jest clearCache.

**Comment by patricksmms** [comment]
@mainfraame weirdly the `dist/index.js` line `27` (https://npm.runkit.com/cucumber-jest/dist/index.js?t=1613075263039) is still showing
```ts
import {exec} from 'cucumber-jest/dist/exec';            
```
instead of https://github.com/mainfraame/cucumber-jest/pull/6/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R35

So still not working on node 10 :( 
```sh
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { exec } from 'cucumber-jest/dist/exec';
                                                                                                    ^

    SyntaxError: Unexpected token {
```

**Comment by mainfraame** [comment]
@patricksmms  my fault. I merged a refactor i had stashed. i'll push up another patch right now

**Comment by patricksmms** [comment]
Right - I just realized now that there was a change on the file.
Thanks!

**Comment by mainfraame** [comment]
@patricksmms go ahead and try 0.1.3. reply here if you're still having the issue.

**Comment by patricksmms** [comment]
@mainfraame it works well now, thanks!

**Pull request merged**
